
[tool.pyflow]
name = "geojson_leaflet"
py_version = "3.8"
version = "0.1.0"
authors = ["Stefan Hagen <stefan@hagen.link>"]

[tool.pyflow.scripts]

[tool.pyflow.dependencies]
geojson = "^2.5.0"

[tool.pyflow.dev-dependencies]
black = "^20.8.0b1"
coverage = "^5.3.0"
flake8 = "^3.8.4"
mypy = "^0.790.0"
pylint = "^2.6.0"
pyperf = "^2.0.0"
pytest = "^6.1.2"
